; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
build_src_filter =
  +<*>
  -<test/*>
debug_test = native/interactions/test_crossfade_interactions
test_filter =
  native/core/test_event_bus
  native/interactions/test_boot_interactions
  native/interactions/test_bypass_interactions
  native/interactions/test_crossfade_interactions
  native/interactions/test_expr_interactions
  native/interactions/test_fsm_filtering
  native/interactions/test_pot_interactions
  native/interactions/test_preset_bank_interactions
  native/interactions/test_preset_interactions
  native/interactions/test_program_change_interactions
  native/interactions/test_program_mode_interactions
  native/interactions/test_settings_interactions
  native/interactions/test_tap_interactions
  native/interactions/test_tempo_interactions
  native/interactions/test_ui_interactions
  native/logic/test_crossfade_handler
  native/logic/test_expr_handler
  native/logic/test_fv1_handler
  native/logic/test_memory_handler
  native/logic/test_menu_handler
  native/logic/test_midi_handler
  native/logic/test_pot_handler
  native/logic/test_preset_handler
  native/logic/test_tap_handler
  native/logic/test_tempo_handler
  native/services/test_bypass_service
  native/services/test_crossfade_service
  native/services/test_expr_service
  native/services/test_fsm_service
  native/services/test_fv1_service
  native/services/test_menu_service
  native/services/test_midi_service
  native/services/test_pot_service
  native/services/test_preset_bank_service
  native/services/test_preset_service
  native/services/test_program_mode_service
  native/services/test_program_service
  native/services/test_settings_service
  native/services/test_tap_service
  native/services/test_tempo_service
lib_deps =
  throwtheswitch/Unity@^2.6.1
